DD_belatedPNG.fix('#bg-wrapper');
DD_belatedPNG.fix('#slogan');
DD_belatedPNG.fix('#logo');
DD_belatedPNG.fix('#logo a');
DD_belatedPNG.fix('#logo img');
DD_belatedPNG.fix('.title');
DD_belatedPNG.fix('.alt-title');
DD_belatedPNG.fix('.category');
DD_belatedPNG.fix('.more');
DD_belatedPNG.fix('#prev');
DD_belatedPNG.fix('#prev a');
DD_belatedPNG.fix('#next');
DD_belatedPNG.fix('#next a');
DD_belatedPNG.fix('.wp-caption');
DD_belatedPNG.fix('.portfolio_thumb');
DD_belatedPNG.fix('.comment');
DD_belatedPNG.fix('.depth-1');
DD_belatedPNG.fix('.avatar');
DD_belatedPNG.fix('#respond');
DD_belatedPNG.fix('#respond h3');
DD_belatedPNG.fix('#author');
DD_belatedPNG.fix('#url');
DD_belatedPNG.fix('#email');
DD_belatedPNG.fix('#comment');
DD_belatedPNG.fix('#submit');
DD_belatedPNG.fix('#advert_125x125');
DD_belatedPNG.fix('.widget');
DD_belatedPNG.fix('.widget h2');
DD_belatedPNG.fix('.entry blockquote');
DD_belatedPNG.fix('.blockquote');
DD_belatedPNG.fix('.widget ul li a');
DD_belatedPNG.fix('.widget ul li a:hover');
DD_belatedPNG.fix('#twitter_widget ul li');
DD_belatedPNG.fix('#search_widget');
DD_belatedPNG.fix('.field');
DD_belatedPNG.fix('.icon-delicious');
DD_belatedPNG.fix('.icon-digg');
DD_belatedPNG.fix('.icon-twitter');
DD_belatedPNG.fix('.icon-flickr');
DD_belatedPNG.fix('.icon-youtube');
DD_belatedPNG.fix('.icon-lastfm');
DD_belatedPNG.fix('.icon-linkedin');
DD_belatedPNG.fix('.icon-stumble');
DD_belatedPNG.fix('.icon-facebook');
